### ISSUE TITLE
install: create `$PREFIX/etc/flux/imp/conf.d` directory, include default `imp.toml`?

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-security#117]
In the [system admin guide](https://flux-framework.readthedocs.io/en/latest/adminguide.html#flux-security-config), there is an instruction to create an `imp.toml` in `/etc/flux/imp/conf.d`.  Neither the `/etc/flux/imp` nor the `/etc/flux/imp/conf.d` directories are created as part of the flux-security installation.  As a convenience to users/sysadmins, maybe we can create those directories as part of the install?

Additionally, it would be cool if we could provide a default `imp.toml` in that directory, but I'm assuming there are security implications there since that defines allowed users and allowed shells.

**Comment by grondo** [comment]
Good question. It is probably reasonable to have the RPM "own" the directory, but we want to be sure that after install of the RPM the system admin would have to "opt in" to using the IMP. It may be safe to install an empty config file (it should be), but I also think it is OK to have the admin carefully follow instructions in order to activate the IMP. Therefore, I think it is probably fine to not install an empty config file on their behalf. (But just my opinion.)

**Comment by grondo** [comment]
I think we decided installing example config files for a security project wasn't a great idea.
